### ISSUE TITLE
Termux not compile cmdtab

### ISSUE THREAD

**Issue by brunodavi** [ethanbaker/cpick#1]
I would like to know how to install this in termux

> Never used go so it may be that some command is missing that I didn't know.

```bash
$ go install ./cmd/cpick
go: downloading github.com/ethanbaker/colors v0.0.0-20210129164941-24dfc6518fbf
go: downloading github.com/gdamore/tcell/v2 v2.3.3
go: downloading github.com/rwxrob/cmdtab v0.10.2
go: downloading code.rocketnine.space/tslocum/cbind v0.1.5
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading github.com/mattn/go-runewidth v0.0.10
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading gitlab.com/ethanbakerdev/colors v0.0.0-20200516034746-6377d14b7978
go: downloading github.com/gdamore/tcell v1.4.0
go: downloading github.com/gdamore/encoding v1.0.0
go: downloading golang.org/x/sys v0.0.0-20210309040221-94ec62e08169
go: downloading golang.org/x/term v0.0.0-20210220032956-6a3ed077a48d
go: downloading golang.org/x/text v0.3.5
# github.com/rwxrob/cmdtab
../../go/pkg/mod/github.com/rwxrob/cmdtab@v0.10.2/others.go:6:12: undefined: winsize
```

**Comment by ethanbaker** [comment]
While I could not replicate this issue on my end, it looks as if this issue comes from a spelling error in an arbitrary file from one of the imported packages. 

This line is present at the top of the file with said error:
```golang
// +build aix js nacl plan9 windows android solaris
```

This indicates that the library is using a build constraint that when met causes the library to break. I will be submitting an issue request to this library immediately, which should hopefully fix this build issue.


If you want to install cpick before the issue is resolved, you can follow these steps:
1. Clone [cpick](https://github.com/ethanbaker/cpick) 
2. Clone the library [cmdtab](https://github.com/rwxrob/cmdtab) while in the cpick directory. This new directory should appear as a subfolder *inside* of cpick.
3. Remove the file `others.go` from the cmdtab repository.
4. Add the line `replace github.com/rwxrob/cmdtab => ./cmdtab` into the `go.mod` file in the cpick directory. 
5. Run the `go install` command inside of the `cmd/cpick` directory.

This should install cpick onto your system. Let me know if this doesn't work and I'll try to draft another fix!

**Comment by brunodavi** [comment]
@ethanbaker could you help me again please

When I run `go install ` returns this error message

```
$ cd cmd/cpick
$ go install
go: errors parsing go.mod:
/data/data/com.termux/files/home/github/cpick/go.mod:15:2: usage: require module/path v1.2.3
```

Here are the steps you had suggested to me

<details>
<summary>repo cpick</summary>

>  How is the repository
```
$ git status --short
M go.mod
?? cmdtab/
```


> Modifications
```diff
$ git diff

diff --git a/go.mod b/go.mod
index 4877e0a..e3ba241 100644
--- a/go.mod
+++ b/go.mod
@@ -12,5 +12,5 @@ require (
 	github.com/lucasb-eyer/go-colorful v1.2.0
 	github.com/mattn/go-runewidth v0.0.10
 	github.com/rivo/uniseg v0.2.0
-	github.com/rwxrob/cmdtab v0.10.2 // indirect
+	./cmdtab
 )
```
</details>

<details>
<summary>repo cpick/cmdtab</summary>

>  How is the repository
```
$ git status --short
 D others.go
```

```diff
$ git diff
diff --git a/others.go b/others.go
deleted file mode 100644
index e43bfcd..0000000
--- a/others.go
+++ /dev/null
@@ -1,7 +0,0 @@
-// +build aix js nacl plan9 windows android solaris
-
-package cmdtab
-
-func init() {
-	WinSize = winsize{80, 40, 100, 100} // complete fudge for lesser OSes
-}
```

</details>

**Comment by brunodavi** [comment]
As I was root I managed to remove the `~/go/pkg/mod/github.com/rwxrob/cmdtab@v0.10.2/others.go`

with that I had no errors in the installation
